### ISSUE TITLE
Feature suggestion: Integration with AppWrite? 

### ISSUE THREAD

**Issue by barshag** [usebasejump/basejump#33]
It would be great to choose different BaaS....

**Comment by tiniscule** [comment]
Interesting - hadn't heard of this.  Is it similar to Supabase in that it uses postgrest?

**Comment by barshag** [comment]
I think it's different DB which managed by the platform + it's doing all
the auth for you.

It will be a great feature to have in basejump - as it appear to be a
growing product and community.

**Comment by barshag** [comment]
Is it completed and working? Can you refer to the docs how to use it?
