### ISSUE TITLE
Question about teams feature

### ISSUE THREAD

**Issue by jamesthesken** [usebasejump/basejump#35]
Just want to say thank you again for your amazing work. Wanted to see if I could get some feedback on an idea I have to extend the teams functionality. This might actually just be a SQL question... but figured it might help someone else.

My application is requiring an `organization` feature. An `organization` can have many `teams`, and its purpose is for admin of the organization to view all data within a team. For example, a school (organization) would have many classes (teams), which would have many users (students/teachers). An organization would have admin users that wouldn't necessarily belong to any team.

I'm not sure if there would be a way to "bolt" this onto basejump. 

One of the approaches I thought of  is to keep the accounts and account_user tables as-is and create a new table called `teams`. The teams table would have a foreign key `account_id` to associate it with an account (organization). Doing so would keep the roles/permissions in place. I would only need to create similar roles/permissions for the teams table.

Appreciate any feedback, thank you.

**Comment by tiniscule** [comment]
Interesting.  You could definitely add a new layer of teams, but I'm curious if it's needed.  Are you doing any billing at the organization level?

If not, you could just leverage team accounts as-is and have users belong to many accounts.

If you do need that organization layer, then yeah I think I'd look at adding a `teams` table with an `account_id`, then a `team_users` table with a `user_id` and `account_id`.  

Adding a second layer of permissions wouldn't be terrible, but could definitely see it getting a bit confusing over time.  You could copy the same logic basically that I've got for the permission check functions.

**Comment by jamesthesken** [comment]
Appreciate you taking the time to write back, thank you. The billing would be at the organization level, so the plan I'm thinking of is something like:

* Create the new `teams` and `teams_users` tables with foreign keys
* Create new permissions such that members of an organization can be still be invited to an org/team, but cannot create new orgs/teams unless they are a subscriber.
* When a user signs up, the main dashboard will show Organizations they belong to (if any). They can only create new ones if they subscribe. 

Hoping it doesn't get too complicated, but I'll report back in case it helps anyone else.

**Comment by tiniscule** [comment]
Makes sense - as long as billing doesn't change from org level I think you'll be ok with that plan.  For permissions if you don't need per-team specific permissions could introduce a new account level one for `team-admin` or similar.  But if you want individual per-team permissions then yeah, I think you'd be taking the core basejump models and duplicating them.

Another option might be to add a column to account_users for account_team_id.  Then could layer in a concept of "global account user" and "specific team user".  You'd have to update the permission lookup functions to do what yo uwant though.  I think that would give you a cleaner data model, but larger changes to core models so all tests would fail/need to be updated also unfortunately.  In that case, if you had a user who  belonged to 2 teams, they'd have 2 records in account_users if that makes sense

**Comment by tconroy** [comment]
Hey @jamesthesken, I am looking to do something very similar in my app (org -> team -> user hierarchy). Curious if you got this working in a satisfactory way / if it'd be possible for you to share what you did (or any code)? Thanks!

**Comment by jamesthesken** [comment]
Hello there @tconroy! It wasn't pretty, but essentially went with the steps above. I didn't have time to make the tests pass or anything.. I'll take another look at my code

**Comment by tioluwani94** [comment]
> Interesting. You could definitely add a new layer of teams, but I'm curious if it's needed. Are you doing any billing at the organization level?
> 
> If not, you could just leverage team accounts as-is and have users belong to many accounts.
> 
> If you do need that organization layer, then yeah I think I'd look at adding a `teams` table with an `account_id`, then a `team_users` table with a `user_id` and `account_id`.
> 
> Adding a second layer of permissions wouldn't be terrible, but could definitely see it getting a bit confusing over time. You could copy the same logic basically that I've got for the permission check functions.

Hi @tiniscule, thank you so much for this awesome project. I'm a Frontend developer and a newbie to Supabase and Postgres, I'd really appreciate it if you could point me in the right direction to implement leveraging the team account as-is and having users belong to many accounts as mentioned here.
