### ISSUE TITLE
I can't create a team from my deploy version

### ISSUE THREAD

**Issue by JeromeHdz** [usebasejump/basejump#39]
Hello,

I have a problem with my deploy version. 

On my local server when I sign up it automatically creates an 'account_user'

Yet when I deployed the project on Vercel and I sign up, I only have a profile user but no 'account-user associated'

(I have not setup Stripe, don't know if it has an impact on the deploy version, in addition, I 'enable_personal_accounts' in my db. 

Could you help me with it? :)

**Comment by tiniscule** [comment]
Hey there - the seed file doesn't run on a production deploy, so make sure you've got the settings similar to what you have set there for local development. You can check it out here https://github.com/usebasejump/basejump/blob/main/supabase/seed.sql

**Comment by JeromeHdz** [comment]
Yeah I checked it and everything was correct still, not working :s
