### ISSUE TITLE
Add STRIPE_WEBHOOK_SECRET to sample env

### ISSUE THREAD

**Issue by kawallis** [usebasejump/basejump#40]
https://github.com/usebasejump/basejump/blob/da5b034e15d0344cb9c883d524db9ce57ae9b5f1/.env.sample#L4

Struggled to figure out while my web hooks were failing but noticed that it was due to not having the `STRIPE_WEBHOOK_SECRET` env set which isn't mention in the docs or referenced in the sample .env. Perhaps it makes since to add it.

**Comment by tiniscule** [comment]
All examples have been updated in the newest release.  thanks for the report!
