### ISSUE TITLE
00000000000000_dbdev_temp_install.sql fails to apply

### ISSUE THREAD

**Issue by Enalmada** [usebasejump/basejump#43]
I installed supabase `v1.77.9` on windows, cloned the basejump repo and ran `supabase start` but getting this error:
```
Applying migration 00000000000000_dbdev_temp_install.sql...
ERROR: Resolving timed out after 1000 milliseconds (SQLSTATE XX000)
At statement 5: create extension "supabase-dbdev"
```

I tried removing that `00000000000000_dbdev_temp_install.sql` file after reading some notes that perhaps dbdev already exists but get another error 
```
Applying migration 00000000000001_utility_functions.sql...
ERROR: schema "dbdev" does not exist (SQLSTATE 3F000)                 
At statement 1: select dbdev.install('basejump-supabase_test_helpers')
```

Is there a version of superbase this no longer works with?

**Comment by kawallis** [comment]
I have experienced this as well. Found any workaround?

**Comment by tiniscule** [comment]
This is due to some latency restrictions in how the installer works.  It's been more solid lately in my testing so I'm closing this for now.  Thanks for the report!
