### ISSUE TITLE
`/dashboard/teams/[accountId]/settings/*` pages not protected from team members

### ISSUE THREAD

**Issue by gmarcus** [usebasejump/basejump#48]
Great project so far.

Found an edge case when I have a team member (not owner) that is able to access settings pages. Even though the sidebar hides the menu item `Settings`, a member can simply enter the URLs for the settings.

RLS prevents a team member from updating settings, but they should not be able to view/interact with the pages at all.

Here is a screenshot of a team member that is able to view the the settings/members page:

![CleanShot 2023-09-08 at 01 05 20](https://github.com/usebasejump/basejump/assets/111017/21864519-00f8-459b-aec0-3769b9c860ef)

If a member accesses a nested Settings page, they should be redirected to the Team Dashboard.
Even though RLS is taking care of the data, what is a good pattern to protect routes?

**Comment by jamesthesken** [comment]
You could use something like this, I think:

```
const router = useRouter();
const { accountId } = router.query;

const { accountRole } = useTeamRole(accountId as string);

if (accountRole === "member") {
  // push the member back to the home page, dashboard, etc.
  router.push("/");
}

```
