### ISSUE TITLE
Add example on how to allow access to files to team members depending on folder name

### ISSUE THREAD

**Issue by jide** [usebasejump/basejump#52]
Just had to do that. That is what I came up with : 

```sql
create policy "Account members can insert" on storage.objects
    for insert
    to authenticated
    with check (
        bucket_id = '<your bucket name>'
        AND (storage.foldername(name))[1] IN (SELECT (account)::text FROM basejump.get_accounts_with_role() AS account)
    );
```

**Comment by tiniscule** [comment]
oh, I think what I would do there is instead look at the path tokens in storage.objects to avoid the join.

Otherwise it would look the same but that would get you out of a join.

**Comment by jide** [comment]
Yeah I saw a number of issue about storage objects metadata. 

Cool approach with tokens. Wouldn't have thought about that. I took the folder name thing straight from supabase base docs.

I think we must get rid of the text casting if the folder name is casted though, right ? :
```sql
create policy "Account members can insert" on storage.objects
    for insert
    to authenticated
    with check (
        bucket_id = '<your bucket name>'
        AND (path_tokens[1]::uuid IN (SELECT FROM basejump.get_accounts_with_role() AS account))
    );
```

**Comment by jide** [comment]
In fact that won't work if there are other folders with names that are not uuids, it will throw "ERROR:  invalid input syntax for type uuid: xxxx", so casting to text is preferable.

**Comment by tiniscule** [comment]
got it - yeah I made a few assumptions there about your setup that probably weren't helpful.

I can't think of a reason not to use the path tokens, so I'm surprised their docs used the folder name.  I'll check it out.
