### ISSUE TITLE
Any plans to check for billing status in RLS ?

### ISSUE THREAD

**Issue by jide** [usebasejump/basejump#56]
Is there any plan to enable RLS at the billing level ?

E.g. Restrict row creation if billing status is not active ?

More generally, I was wondering how you handle restriction based on billing status ?

**Comment by tiniscule** [comment]
Right now I'm doing client side checks with the billing endpoints and popping up a modal - but I tend to lean towards softer account blocks than outright disabling them.

Would be an easy thing to add - and easy to do in your own RLS policies by checking the basejump.billing_subscriptions status column using the account ID.

I wonder if I should extend the account lookup function to take an active variable, then would only return active account IDs and skip any delinquent. 🤔

**Comment by jide** [comment]
Thank you for your answer. In my case I think checks on the server side will be fine.

**Comment by tiniscule** [comment]
Closing for now, I've made a note for a future version.  I'm blocked from updates right now until Supabase launches the new dbdev version 😬
