### ISSUE TITLE
error: Module not found lib/types/supabase.ts".

### ISSUE THREAD

**Issue by taha2002** [usebasejump/basejump#58]
when i try to deploy the function to supabase, I get 

`Error: failed to load 'https://deno.land/x/basejump@v2.0.1/billing-functions/lib/types/supabase.ts': Module not found "https://deno.land/x/basejump@v2.0.1/billing-functions/lib/types/supabase.ts".
error running container: exit 1`

this error in 
at https://deno.land/x/basejump@v2.0.1/billing-functions/lib/create-supabase-client.ts:2:26

is trying to import file supabase.ts but it doesn't exist

**Comment by williambarberjr** [comment]
I'm getting the same error

**Comment by tiniscule** [comment]
Waiting for tests to pass on a fix - sorry about that I'm not what happened there

**Comment by tiniscule** [comment]
This has been resolved.  You'll want to bump your Deno edge functions to `v2.0.3`: https://deno.land/x/basejump@v2.0.3
