### ISSUE TITLE
Can we use basejump with hosted supabase?

### ISSUE THREAD

**Issue by airsherlock** [usebasejump/basejump#72]
The installation at https://usebasejump.com/docs/installation is a bit unclear on how to go about using basejump with hosted supabase.

Any pointers here?

**Comment by hankmander** [comment]
I set up database migrations and pushed them to the hosted supbase like [here](https://supabase.com/docs/guides/cli/local-development#database-migrations)

**Comment by tiniscule** [comment]
You can, but it expects that you're doing local dev.  You could recreate the migrations in the manual directions in the hosted SQL editor though.

If you're doing local dev, you can deploy your migrations to the hosted production env like this: https://usebasejump.com/docs/deployment
