### ISSUE TITLE
Webhook doesnt exist even though its in documentation?

### ISSUE THREAD

**Issue by salvinoto** [usebasejump/basejump#79]
When I run this edge function, I get a 404 error. 
<img width="356" alt="Screenshot 2024-03-27 at 9 39 59 PM" src="https://github.com/usebasejump/basejump/assets/54959187/bcd14e6d-9349-4f46-9d21-98dd5a55b24a">
These are the only Supabase edge function there are. Is this a mistake in the docs?

```
const {data, error} = await supabase.functions.invoke('current_user_account_role', {
    body: {
        action: "get_plans",
        args: {
            account_id: "uuid"
        }
    }
});
```

```
 FunctionsHttpError {
    name: 'FunctionsHttpError',
    context: Response {
      type: 'basic',
      url: 'http://localhost:54321/functions/v1/current_user_account_role',
      redirected: false,
      status: 404,
      ok: false,
      statusText: 'Not Found',
```

**Comment by salvinoto** [comment]
Changed it to billing-function and it works now, just a mistake in the docs

**Comment by tiniscule** [comment]
Pushed a fix for this - sorry for the confusion there
