### ISSUE TITLE
Using UUIDs for primary keys

### ISSUE THREAD

**Issue by vangelov** [usebasejump/basejump#91]
Hello, first of all I want to thank you for creating basejump. It seems really well-made. 

I noticed that the command `npx @usebasejump/cli@latest generate table` creates tables with uuid for primary keys. Apart from being able to create the primary key from the client, does this have other advantages over sequential integer keys? Also, could be there be any performance implications?

**Comment by tiniscule** [comment]
with postgres the costs are pretty minimal for uuid.  There are benefits as your datasets grow and things get more complicated.  The biggest downside you'll see day to day is that you'll need to maintain your own timestamps for things like created at ordering since they aren't sequential.
