### ISSUE TITLE
Change default schema of basejump installation

### ISSUE THREAD

**Issue by chbert** [usebasejump/basejump#92]
Hi there,
First, thanks for the great library! I'm try to follow the hardening guide by supabase: https://supabase.com/docs/guides/database/hardening-data-api

Is there a way to tell basejump to use another schema than "public" for installing the functions?

**Comment by tiniscule** [comment]
Basejump installs the sensitive functions inside the `basejump` schema.  the only ones int he public namespaces are the ones that you'd need access to through the API.  They should be locked down with auth checks for you.
