### ISSUE TITLE
Where is the billing-functions code?

### ISSUE THREAD

**Issue by Pietervdw** [usebasejump/basejump#93]
Hi there,

Apologies if this is an obvious thing, but I can't find the code for the billing-functions? In which file are the actual code for these functions? Documentation mentions them: https://usebasejump.com/docs/billing

The ones I'm looking for:
- get_plans
- get_billing_status

**Comment by mabaranowski** [comment]
https://github.com/usebasejump/basejump/tree/v2.0.3/supabase/functions/deno-packages

**Comment by Pietervdw** [comment]
Thanks!
